1. Importe numpy como 'np' e imprima o número da versão instalada no ambiente (local ou colab).

In [1]:
import numpy as np
np.version

<module 'numpy.version' from 'c:\\Users\\Mirella\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\version.py'>

2. Crie um *array* 1D com números de 0 a 9 e imprima o resultado.

In [2]:
a = np.array(range(10))
print(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Crie uma matriz booleana de 3x3 e preencha os seus valores com 'True'. Imprima o resultado.
Dica: Verifique o uso da função full na documentação do numpy.

In [3]:
matriz_bool = np.full ((3, 3), True)
print(matriz_bool)
matriz_bool

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. Crie um *array* 1D como números inteiros (50 elementos) de 0 a 1000 e **extraia** apenas os números pares. Imprima o resultado.

In [4]:
num_int = np.random.randint(0, 1000, 50)
print(num_int)
pares = num_int[num_int%2==0]
print(pares)

[958 520 720 411 805 719   1 832 429 565 126 169 931 652 930 548 950 579
 478 254 790 231  33 937 147 385 922 530 995 714 841 442 915 708 221 198
 957 172 231 260 950 675 205 542 494 330  43 410 336 301]
[958 520 720 832 126 652 930 548 950 478 254 790 922 530 714 442 708 198
 172 260 950 542 494 330 410 336]


5. Usando o *array* criando no exercício anterior, **substitua** todos os números ímpares maiores que 50 por -1 no *array* original. 

In [5]:
num50 = num_int[num_int > 50]
num50[num50 %2 != 0] = -1
num50

array([958, 520, 720,  -1,  -1,  -1, 832,  -1,  -1, 126,  -1,  -1, 652,
       930, 548, 950,  -1, 478, 254, 790,  -1,  -1,  -1,  -1, 922, 530,
        -1, 714,  -1, 442,  -1, 708,  -1, 198,  -1, 172,  -1, 260, 950,
        -1,  -1, 542, 494, 330, 410, 336,  -1])

6. Usando o *array* criando no exercício anterior, **substitua** todos os números ímpares com o valor -1 **sem** alterar o *array* original.

In [6]:
num_int2 = num_int.copy()
num_int2[num_int%2!=0] = -1
num_int2

array([958, 520, 720,  -1,  -1,  -1,  -1, 832,  -1,  -1, 126,  -1,  -1,
       652, 930, 548, 950,  -1, 478, 254, 790,  -1,  -1,  -1,  -1,  -1,
       922, 530,  -1, 714,  -1, 442,  -1, 708,  -1, 198,  -1, 172,  -1,
       260, 950,  -1,  -1, 542, 494, 330,  -1, 410, 336,  -1])

7. Crie um *array* 1D com 100 valores de ponto flutuante (**float**), converta-o em uma matriz 2D com 10 linhas e 10 colunas.

In [7]:
vetor_float = np.round((np.random.rand(100)*100), 2)
vetor_float.reshape((10,10))

array([[35.29, 32.04, 19.63, 35.11, 21.03, 16.79, 93.57, 82.52,  4.65,
        99.46],
       [82.68, 15.33, 52.9 , 84.65, 67.8 , 62.65, 90.83, 78.79, 54.27,
        15.18],
       [ 3.46,  1.77, 51.96,  4.84, 53.8 , 14.35, 45.45, 81.05, 19.73,
        30.1 ],
       [76.48, 51.5 , 85.48, 77.4 , 67.12, 31.28,  1.96, 27.51, 48.87,
        20.18],
       [77.52, 22.38,  4.83, 80.1 , 99.17, 81.59, 88.13, 88.96, 73.87,
        91.29],
       [84.58,  3.82, 30.01, 67.82, 63.28, 58.31, 84.02, 72.84, 88.83,
        72.38],
       [76.37,  2.87, 62.78, 64.92, 69.92,  7.46, 66.59,  2.64,  8.15,
        59.64],
       [34.23, 22.27, 46.72, 58.48, 21.59, 84.75, 50.16, 87.07, 55.91,
        84.23],
       [54.57, 25.45, 11.58, 26.49, 38.36, 34.82, 37.91, 13.9 , 63.26,
        27.02],
       [77.81, 49.23, 63.7 , 16.02, 23.67, 64.69, 23.31,  8.21, 41.89,
        28.97]])

Crie duas matrizes 2D de inteiros aleatórios (de 0 a 100) com dimensões 10x10. Empilhe-as horizontalmente.
Dica: verique as funções hstack e concatenate na documentação do numpy

In [8]:
matriz1 = np.random.randint(0, 100, (10,10))
matriz2 = np.random.randint(0, 100, (10,10))
vertical = np.vstack((matriz1, matriz2))
horizontal = np.hstack((matriz1, matriz2))
print(horizontal)


[[25 50 37 13 67 72  0 68 91 42 11 15 16 19 63 81 53 24 15 11]
 [63 57  8 85 27 75 18 56 83 78 23 64 80 54 83 91 99  7 89 26]
 [61 84 43 27 85 20 70 62 53 52 22 34 78 67 22 20 22 79 71 63]
 [34 30 68 78 25 19 50 81 78 62 60 13 69 54 41 24 66 34  7 96]
 [30 40 88 36 99 56 85 23 89 91 15 24 26 11 98 93 81 88 44 60]
 [35 32  0 34 41 20 44 60 72 28 42 37  8  0 97 45 53 98 72 77]
 [ 0 80 65 91 86  5 74 25  7  9 51 86 70 11 94 12 99 79 10 55]
 [11  7 78 56 85 41 52 82 44  8  7 60 33 55 32 30 26 79 40 57]
 [78 83 80 38 53 17 21 79 86 76  9 79 19 99 89 33  3 34  0 79]
 [18 98 53 11 31 47  6 28 25 84 52 70 59 16  3 50 31 21  1 20]]


Crie duas matrizes 2D de inteiros aleatórios (de 0 a 100) com dimensões 10x10. Empilhe-as verticalmente.
Dica: verique as funções vstack e concatenate na documentação do numpy

In [9]:
vertical

array([[25, 50, 37, 13, 67, 72,  0, 68, 91, 42],
       [63, 57,  8, 85, 27, 75, 18, 56, 83, 78],
       [61, 84, 43, 27, 85, 20, 70, 62, 53, 52],
       [34, 30, 68, 78, 25, 19, 50, 81, 78, 62],
       [30, 40, 88, 36, 99, 56, 85, 23, 89, 91],
       [35, 32,  0, 34, 41, 20, 44, 60, 72, 28],
       [ 0, 80, 65, 91, 86,  5, 74, 25,  7,  9],
       [11,  7, 78, 56, 85, 41, 52, 82, 44,  8],
       [78, 83, 80, 38, 53, 17, 21, 79, 86, 76],
       [18, 98, 53, 11, 31, 47,  6, 28, 25, 84],
       [11, 15, 16, 19, 63, 81, 53, 24, 15, 11],
       [23, 64, 80, 54, 83, 91, 99,  7, 89, 26],
       [22, 34, 78, 67, 22, 20, 22, 79, 71, 63],
       [60, 13, 69, 54, 41, 24, 66, 34,  7, 96],
       [15, 24, 26, 11, 98, 93, 81, 88, 44, 60],
       [42, 37,  8,  0, 97, 45, 53, 98, 72, 77],
       [51, 86, 70, 11, 94, 12, 99, 79, 10, 55],
       [ 7, 60, 33, 55, 32, 30, 26, 79, 40, 57],
       [ 9, 79, 19, 99, 89, 33,  3, 34,  0, 79],
       [52, 70, 59, 16,  3, 50, 31, 21,  1, 20]])

Para ler arquivos em formato txt que estão em formato de "tabelas", podemos usar a função genfromtxt() do numpy. Esta função recebe como argumentos: caminho do arquivo txt (path local ou uma url); delimiter para separar cada valor seguindo algum critério; dtype para converter os valores recebidos em algum tipo de dado conhecido (exemplo: float) e; usecols em que é definido o cabeçalho das colunas lidas a partir do arquivo.

Vejamos um exemplo de uso da função genfromtxt sobre a base de dados Iris.

In [10]:
import numpy as np
# Caminho da base de dados é uma url disponível na internet (visite o link abaixo
# pelo navegador para título de curiosidade :))
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# Lê os dados a partir do caminho passado e armazena em uma matriz 2D chamada iris_2d
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [11]:
# matriz 2D criada com os dados da base Iris
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

11. A partir dos dados lidos na matriz iris_2d, filtre as linhas que possuem (coluna 3) > 1.5 e (coluna 1) < 5.0.

In [12]:
linhas = (iris_2d[:, 1] >1.5) & (iris_2d[:, 3] < 5.0)
print(iris_2d[linhas])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

12. A partir dos dados lidos na matriz iris_2d, calcule a **média** e **desvio padrão** de cada coluna presente nos dados. Imprima o resultado.

13. Crie um repositório no Github e versione todos os códigos que desenvolveram nesta lista de exercícios.